version: '2'
services:
  etcd:
    image: elcolio/etcd:latest
    container_name: etcd
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/usr/share/elasticsearch/data
      #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"