version: '2'

services:
  ott_admin_php:
    image: tvblack/php:7.1.8
    container_name: ott_admin_php
    privileged: true
    restart: always
    command: "/usr/local/bin/docker-entrypoint.sh"
    volumes:
      - /data/projects/ott_admin:/var/www/ott_admin
      - /data/session/ott_admin:/var/run/session
      - /data/logs/ott_admin:/data/logs/ott_admin
      - /etc/localtime:/etc/localtime:ro
      - ./php7.1.8/php.ini:/usr/local/etc/php.ini:ro
      - ./php7.1.8/php.conf.d:/usr/local/etc/php-fpm.d:ro
      - /data/logs/ott_admin/php-logs:/var/log/php
      - ./ott_admin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro

  nginx:
    image: nginx:1.12.1-alpine
    container_name: nginx
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/projects/ott_admin:/var/www/ott_admin
      - /data/logs/ott_admin/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    links:
      - ott_admin_php
    ports:
      - 127.0.0.1:8082:80