version: '3'

services:
 redis7001:
  image: redis:5.0
  container_name: redis7001
  restart: always
  command: 
    ["redis-server","/usr/local/etc/redis/redis.conf"]
  volumes:
   - ./redis-cluster/7001/data:/data
   - ./redis-cluster/7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
  environment:
   - REDIS_PORT=7001
   - TZ=Asia/Shanghai
  ports:
    - '7001:7001'       #服务端口
    - '17001:17001'   #集群端口

 redis7002:
   image: redis:5.0
   container_name: redis7002
   restart: always
   command: 
     ["redis-server","/usr/local/etc/redis/redis.conf"]
   volumes:
    - ./redis-cluster/7002/data:/data
    - ./redis-cluster/7002/conf/redis.conf:/usr/local/etc/redis/redis.conf
   environment:
    - REDIS_PORT=7002
    - TZ=Asia/Shanghai
   ports:
     - '7002:7002'       #服务端口
     - '17002:17002'   #集群端口

 redis7003:
   image: redis:5.0
   container_name: redis7003
   restart: always
   command: 
     ["redis-server","/usr/local/etc/redis/redis.conf"]
   volumes:
    - ./redis-cluster/7003/data:/data
    - ./redis-cluster/7003/conf/redis.conf:/usr/local/etc/redis/redis.conf
   environment:
    - REDIS_PORT=7003
    - TZ=Asia/Shanghai
   ports:
     - '7003:7003'       #服务端口
     - '17003:17003'   #集群端口

 redis7004:
   image: redis:5.0
   container_name: redis7004
   restart: always
   command: 
     ["redis-server","/usr/local/etc/redis/redis.conf"]
   volumes:
    - ./redis-cluster/7004/data:/data
    - ./redis-cluster/7004/conf/redis.conf:/usr/local/etc/redis/redis.conf
   environment:
    - REDIS_PORT=7004
    - TZ=Asia/Shanghai
   ports:
     - '7004:7004'       #服务端口
     - '17004:17004'   #集群端口

 redis7005:
   image: redis:5.0
   container_name: redis7005
   restart: always
   command: 
     ["redis-server","/usr/local/etc/redis/redis.conf"]
   volumes:
    - ./redis-cluster/7005/data:/data
    - ./redis-cluster/7005/conf/redis.conf:/usr/local/etc/redis/redis.conf
   environment:
    - REDIS_PORT=7005
    - TZ=Asia/Shanghai
   ports:
     - '7005:7005'       #服务端口
     - '17005:17005'   #集群端口

 redis7006:
   image: redis:5.0
   container_name: redis7006
   restart: always
   command: 
     ["redis-server","/usr/local/etc/redis/redis.conf"]
   volumes:
    - ./redis-cluster/7006/data:/data
    - ./redis-cluster/7006/conf/redis.conf:/usr/local/etc/redis/redis.conf
   environment:
    - REDIS_PORT=7006
    - TZ=Asia/Shanghai
   ports:
     - '7006:7006'       #服务端口
     - '17006:17006'   #集群端口